import { Product, Order } from "./types";

export const mockProducts: Product[] = [
  {
    id: "1",
    title: "Nike Air Max 90",
    description: "Classic Nike Air Max 90 in white/black colorway. Premium leather upper with visible Air cushioning.",
    price: 8999,
    compareAtPrice: 12999,
    category: "Sneakers",
    status: "active",
    inventory: 45,
    image: "https://placehold.co/400x400/1a1a2e/ffffff?text=Nike+Air+Max",
    tags: ["nike", "sneakers", "bestseller"],
    createdAt: "2026-07-01",
    updatedAt: "2026-07-10",
  },
  {
    id: "2",
    title: "Adidas Ultraboost 22",
    description: "Responsive Boost midsole. Primeknit upper for adaptive support.",
    price: 7499,
    compareAtPrice: 9999,
    category: "Sneakers",
    status: "active",
    inventory: 32,
    image: "https://placehold.co/400x400/1a1a2e/ffffff?text=Adidas+UB",
    tags: ["adidas", "sneakers", "running"],
    createdAt: "2026-07-02",
    updatedAt: "2026-07-09",
  },
  {
    id: "3",
    title: "Handmade Jaipur Pottery Set",
    description: "Set of 4 handcrafted ceramic cups from Jaipur. Traditional blue pottery design.",
    price: 1299,
    category: "Home & Living",
    status: "active",
    inventory: 18,
    image: "https://placehold.co/400x400/1a1a2e/ffffff?text=Pottery+Set",
    tags: ["handmade", "jaipur", "pottery", "bestseller"],
    createdAt: "2026-07-03",
    updatedAt: "2026-07-11",
  },
  {
    id: "4",
    title: "Puma RS-X Reinvention",
    description: "Bold chunky silhouette with RS technology. Retro-futuristic design.",
    price: 5999,
    compareAtPrice: 7999,
    category: "Sneakers",
    status: "active",
    inventory: 8,
    image: "https://placehold.co/400x400/1a1a2e/ffffff?text=Puma+RS-X",
    tags: ["puma", "sneakers", "sale"],
    createdAt: "2026-07-04",
    updatedAt: "2026-07-08",
  },
  {
    id: "5",
    title: "Organic Cotton T-Shirt",
    description: "Premium organic cotton. Relaxed fit. Available in 6 colors.",
    price: 899,
    category: "Apparel",
    status: "active",
    inventory: 120,
    image: "https://placehold.co/400x400/1a1a2e/ffffff?text=Cotton+Tee",
    tags: ["organic", "cotton", "apparel"],
    createdAt: "2026-07-05",
    updatedAt: "2026-07-10",
  },
  {
    id: "6",
    title: "Leather Messenger Bag",
    description: "Full grain leather. Brass hardware. Fits 15-inch laptop.",
    price: 3499,
    compareAtPrice: 4999,
    category: "Accessories",
    status: "draft",
    inventory: 0,
    image: "https://placehold.co/400x400/1a1a2e/ffffff?text=Leather+Bag",
    tags: ["leather", "bag", "accessories"],
    createdAt: "2026-07-06",
    updatedAt: "2026-07-11",
  },
  {
    id: "7",
    title: "New Balance 574",
    description: "Iconic silhouette. ENCAP midsole technology. suede/mesh upper.",
    price: 6499,
    category: "Sneakers",
    status: "active",
    inventory: 25,
    image: "https://placehold.co/400x400/1a1a2e/ffffff?text=NB+574",
    tags: ["new balance", "sneakers", "classic"],
    createdAt: "2026-07-07",
    updatedAt: "2026-07-09",
  },
  {
    id: "8",
    title: "Reebok Club C 85",
    description: "Clean low-top design. Soft leather upper. Timeless court style.",
    price: 4999,
    compareAtPrice: 6999,
    category: "Sneakers",
    status: "active",
    inventory: 3,
    image: "https://placehold.co/400x400/1a1a2e/ffffff?text=Reebok+Club",
    tags: ["reebok", "sneakers", "sale"],
    createdAt: "2026-07-08",
    updatedAt: "2026-07-10",
  },
];

export const mockOrders: Order[] = [
  { id: "1", orderNumber: "#1001", customer: "Rahul Sharma", total: 8999, status: "delivered", items: 1, createdAt: "2026-07-10" },
  { id: "2", orderNumber: "#1002", customer: "Priya Patel", total: 2498, status: "shipped", items: 2, createdAt: "2026-07-10" },
  { id: "3", orderNumber: "#1003", customer: "Amit Kumar", total: 7499, status: "processing", items: 1, createdAt: "2026-07-11" },
  { id: "4", orderNumber: "#1004", customer: "Sneha Gupta", total: 5398, status: "pending", items: 3, createdAt: "2026-07-11" },
  { id: "5", orderNumber: "#1005", customer: "Vikram Singh", total: 8999, status: "pending", items: 1, createdAt: "2026-07-11" },
];
