import { Product, Order, Campaign, SocialPost, Agent, AgentLog } from "./types";

export const mockProducts: Product[] = [
  {
    id: "1",
    title: "Nike Air Max 90",
    description: "Classic Nike Air Max 90 in white/black colorway. Premium leather upper with visible Air cushioning.",
    price: 8999,
    compareAtPrice: 12999,
    category: "Sneakers",
    status: "active",
    inventory: 45,
    image: "https://placehold.co/400x400/1a1a2e/ffffff?text=Nike+Air+Max",
    tags: ["nike", "sneakers", "bestseller"],
    createdAt: "2026-07-01",
    updatedAt: "2026-07-10",
  },
  {
    id: "2",
    title: "Adidas Ultraboost 22",
    description: "Responsive Boost midsole. Primeknit upper for adaptive support.",
    price: 7499,
    compareAtPrice: 9999,
    category: "Sneakers",
    status: "active",
    inventory: 32,
    image: "https://placehold.co/400x400/1a1a2e/ffffff?text=Adidas+UB",
    tags: ["adidas", "sneakers", "running"],
    createdAt: "2026-07-02",
    updatedAt: "2026-07-09",
  },
  {
    id: "3",
    title: "Handmade Jaipur Pottery Set",
    description: "Set of 4 handcrafted ceramic cups from Jaipur. Traditional blue pottery design.",
    price: 1299,
    category: "Home & Living",
    status: "active",
    inventory: 18,
    image: "https://placehold.co/400x400/1a1a2e/ffffff?text=Pottery+Set",
    tags: ["handmade", "jaipur", "pottery", "bestseller"],
    createdAt: "2026-07-03",
    updatedAt: "2026-07-11",
  },
  {
    id: "4",
    title: "Puma RS-X Reinvention",
    description: "Bold chunky silhouette with RS technology. Retro-futuristic design.",
    price: 5999,
    compareAtPrice: 7999,
    category: "Sneakers",
    status: "active",
    inventory: 8,
    image: "https://placehold.co/400x400/1a1a2e/ffffff?text=Puma+RS-X",
    tags: ["puma", "sneakers", "sale"],
    createdAt: "2026-07-04",
    updatedAt: "2026-07-08",
  },
  {
    id: "5",
    title: "Organic Cotton T-Shirt",
    description: "Premium organic cotton. Relaxed fit. Available in 6 colors.",
    price: 899,
    category: "Apparel",
    status: "active",
    inventory: 120,
    image: "https://placehold.co/400x400/1a1a2e/ffffff?text=Cotton+Tee",
    tags: ["organic", "cotton", "apparel"],
    createdAt: "2026-07-05",
    updatedAt: "2026-07-10",
  },
  {
    id: "6",
    title: "Leather Messenger Bag",
    description: "Full grain leather. Brass hardware. Fits 15-inch laptop.",
    price: 3499,
    compareAtPrice: 4999,
    category: "Accessories",
    status: "draft",
    inventory: 0,
    image: "https://placehold.co/400x400/1a1a2e/ffffff?text=Leather+Bag",
    tags: ["leather", "bag", "accessories"],
    createdAt: "2026-07-06",
    updatedAt: "2026-07-11",
  },
  {
    id: "7",
    title: "New Balance 574",
    description: "Iconic silhouette. ENCAP midsole technology. suede/mesh upper.",
    price: 6499,
    category: "Sneakers",
    status: "active",
    inventory: 25,
    image: "https://placehold.co/400x400/1a1a2e/ffffff?text=NB+574",
    tags: ["new balance", "sneakers", "classic"],
    createdAt: "2026-07-07",
    updatedAt: "2026-07-09",
  },
  {
    id: "8",
    title: "Reebok Club C 85",
    description: "Clean low-top design. Soft leather upper. Timeless court style.",
    price: 4999,
    compareAtPrice: 6999,
    category: "Sneakers",
    status: "active",
    inventory: 3,
    image: "https://placehold.co/400x400/1a1a2e/ffffff?text=Reebok+Club",
    tags: ["reebok", "sneakers", "sale"],
    createdAt: "2026-07-08",
    updatedAt: "2026-07-10",
  },
];

export const mockOrders: Order[] = [
  { id: "1", orderNumber: "#1001", customer: "Rahul Sharma", total: 8999, status: "delivered", items: 1, createdAt: "2026-07-10" },
  { id: "2", orderNumber: "#1002", customer: "Priya Patel", total: 2498, status: "shipped", items: 2, createdAt: "2026-07-10" },
  { id: "3", orderNumber: "#1003", customer: "Amit Kumar", total: 7499, status: "processing", items: 1, createdAt: "2026-07-11" },
  { id: "4", orderNumber: "#1004", customer: "Sneha Gupta", total: 5398, status: "pending", items: 3, createdAt: "2026-07-11" },
  { id: "5", orderNumber: "#1005", customer: "Vikram Singh", total: 8999, status: "pending", items: 1, createdAt: "2026-07-11" },
];

export const mockCampaigns: Campaign[] = [
  {
    id: "1",
    name: "Summer Sale 2026",
    type: "social",
    status: "active",
    platform: "Instagram",
    reach: 12500,
    engagement: 890,
    conversions: 47,
    createdAt: "2026-07-08",
  },
  {
    id: "2",
    name: "New Arrivals Email",
    type: "email",
    status: "completed",
    reach: 3200,
    engagement: 640,
    conversions: 23,
    createdAt: "2026-07-05",
  },
  {
    id: "3",
    name: "Google Shopping Ads",
    type: "ad",
    status: "active",
    platform: "Google",
    reach: 45000,
    engagement: 2100,
    conversions: 89,
    createdAt: "2026-07-01",
  },
  {
    id: "4",
    name: "Flash Sale Announcement",
    type: "social",
    status: "scheduled",
    platform: "Twitter",
    reach: 0,
    engagement: 0,
    conversions: 0,
    createdAt: "2026-07-11",
  },
];

export const mockSocialPosts: SocialPost[] = [
  {
    id: "1",
    platform: "instagram",
    content: "🔥 Summer Sale is LIVE! Up to 40% off on all sneakers. Link in bio!",
    image: "https://placehold.co/600x600/1a1a2e/ffffff?text=Summer+Sale",
    status: "published",
    likes: 234,
    comments: 18,
    shares: 12,
  },
  {
    id: "2",
    platform: "twitter",
    content: "New drop alert 🚀 Handmade Jaipur Pottery now available. Each piece unique. #Handmade #Jaipur",
    status: "published",
    likes: 89,
    comments: 7,
    shares: 23,
  },
  {
    id: "3",
    platform: "instagram",
    content: "Behind the scenes: How our leather bags are made 🎥 Full reel coming soon!",
    image: "https://placehold.co/600x600/1a1a2e/ffffff?text=BTS+Reel",
    status: "scheduled",
    scheduledFor: "2026-07-12 09:00",
  },
  {
    id: "4",
    platform: "linkedin",
    content: "We're hiring! Looking for a growth marketer to join our team. DM for details.",
    status: "draft",
  },
];

export const mockAgents: Agent[] = [
  {
    id: "1", name: "Product Lister", department: "storeops", type: "ondemand",
    status: "idle", runsToday: 3, tokensUsed: 12500,
    description: "Creates products from voice, image, or text input",
  },
  {
    id: "2", name: "Pricing Strategist", department: "storeops", type: "ondemand",
    status: "idle", runsToday: 2, tokensUsed: 8900,
    description: "Analyzes competitors and recommends pricing",
  },
  {
    id: "3", name: "Inventory Tracker", department: "storeops", type: "cron",
    status: "active", schedule: "Every 6h", lastRun: "12:00 PM", nextRun: "6:00 PM",
    runsToday: 2, tokensUsed: 4200,
    description: "Monitors stock levels and predicts stockouts",
  },
  {
    id: "4", name: "Social Media Manager", department: "marketing", type: "ondemand",
    status: "idle", runsToday: 1, tokensUsed: 6700,
    description: "Generates and schedules social media posts",
  },
  {
    id: "5", name: "Content Creator", department: "marketing", type: "ondemand",
    status: "running", runsToday: 2, tokensUsed: 15200,
    description: "Generates product images, carousels, and graphics",
  },
  {
    id: "6", name: "Engagement Responder", department: "marketing", type: "cron",
    status: "active", schedule: "Every 30m", lastRun: "2:30 PM", nextRun: "3:00 PM",
    runsToday: 12, tokensUsed: 8400,
    description: "Monitors and replies to comments and DMs",
  },
  {
    id: "7", name: "Support Agent", department: "customer-brand", type: "cron",
    status: "active", schedule: "Every 15m", lastRun: "2:45 PM", nextRun: "3:00 PM",
    runsToday: 24, tokensUsed: 18600,
    description: "Handles customer queries and drafts responses",
  },
  {
    id: "8", name: "Brand Guardian", department: "customer-brand", type: "ondemand",
    status: "active", runsToday: 5, tokensUsed: 3200,
    description: "Enforces brand voice across all content",
  },
  {
    id: "9", name: "Competitor Monitor", department: "storeops", type: "cron",
    status: "paused", schedule: "Every 2h", lastRun: "10:00 AM", nextRun: "Paused",
    runsToday: 0, tokensUsed: 0,
    description: "Tracks competitor prices and products",
  },
];

export const mockAgentLogs: AgentLog[] = [
  { id: "1", agentId: "3", agentName: "Inventory Tracker", action: "Checked 8 products. 1 low stock alert.", result: "warning", timestamp: "2:30 PM", details: "SKU-1234 has 12 units remaining" },
  { id: "2", agentId: "7", agentName: "Support Agent", action: "Auto-resolved 3 tickets (order status queries)", result: "success", timestamp: "2:15 PM" },
  { id: "3", agentId: "5", agentName: "Content Creator", action: "Generating Instagram carousel for Summer Sale", result: "success", timestamp: "2:00 PM" },
  { id: "4", agentId: "6", agentName: "Engagement Responder", action: "Replied to 5 Instagram comments", result: "success", timestamp: "1:30 PM" },
  { id: "5", agentId: "2", agentName: "Pricing Strategist", action: "Recommended price drop for 3 products", result: "success", timestamp: "1:00 PM" },
  { id: "6", agentId: "1", agentName: "Product Lister", action: "Created product: Nike Air Max 90", result: "success", timestamp: "12:30 PM" },
  { id: "7", agentId: "9", agentName: "Competitor Monitor", action: "Connection timeout — paused", result: "error", timestamp: "10:00 AM", details: "Failed to reach competitor URL after 3 retries" },
];
